apiVersion: apps/v1
kind: Deployment
metadata:
  name: appbackend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appbackend
  template:
    metadata:
      labels:
        app: appbackend
    spec:
      containers:
        - name: appbackend
          image: muriloalencs/backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appbackend-service
spec:
  type: ClusterIP
  selector:
    app: appbackend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
