apiVersion: apps/v1
kind: Deployment
metadata:
  name: appfrontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appfrontend
  template:
    metadata:
      labels:
        app: appfrontend
    spec:
      containers:
        - name: appfrontend
          image: muriloalencs/frontend
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://appbackend-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: appfrontend-service
spec:
  type: NodePort
  selector:
    app: appfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
