apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  FLASK_APP: "run.py"
  FLASK_DB_TYPE: "postgres"
  FLASK_DB_USER: "myuser"
  FLASK_DB_NAME: "mydb"
  FLASK_DB_PASSWORD: "mypassword"
  FLASK_DB_HOST: "postgres-service"
  FLASK_DB_PORT: "5432"
